
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems?useSSL=false
    username: root
    password: Bibl@77514

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update